import { Button } from 'assets/styles/buttons'
import { adjustURLImage } from 'helpers/adjustURLImage'
import moment from 'moment'
import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { getParties, PartyProps } from 'services/party'
import { Wrapper } from './styles'

type HomeProps = {
  parties: PartyProps[]
}

const Home = ({ parties }: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Partytime | Acompanhe as festas!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper className='container'>
        <h1>Acompanhe as festas do momento!</h1>
          {parties && parties.length > 0
            ? <div className='grid'>
                {parties.map(party => (
                  <div key={party._id} className="party">
                    <div>
                      <img src={party.photos ? adjustURLImage(party.photos[0]) : ''} alt={party.title} />
                    </div>
                    <div>
                      <h3>{party.title}</h3>
                      <h4>Data: {moment(party.partyDate).format('DD/MM/YYYY')}</h4>
                      <Link href={`party/${party._id}`}>
                        <Button>Ver Mais</Button>
                      </Link>
                    </div>
                  </div>
                ))}
              </div>
            : <h2>Estamos sem festas no momento. <Link href={'/register'}>Por favor, se cadastre e crie sua propria festa!</Link> </h2>}
      </Wrapper>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { parties } = await getParties()

  console.log(parties)

  return {
    props: {
      parties
    }
  }
}
