import { adjustURLImage } from 'helpers/adjustURLImage'
import moment from 'moment'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { getPartyByIdRequest, PartyProps } from 'services/party'
import { Wrapper } from './styles'

type PartyDetailsProps = {
    party: PartyProps
}

const PartyDetails = ({ party }: PartyDetailsProps) => {
  return (
        <div>
            <Head>
            <title>Partytime | {party.title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper className='container'>
                <h1>{party.title}</h1>
                <div className='d-flex'>
                  <div className='images'>
                      <div className='big'>
                        <img src={party.photos ? adjustURLImage(party.photos[0]) : '/img/partytimelogo.png' } />
                      </div>
                      <div className='small-imgs'>
                        {party.photos && party.photos?.length > 1
                          ? <>
                            {party.photos.slice(1).map((photo, count) => (
                              <div key={photo} className="small">
                                <img src={adjustURLImage(photo)} alt="Festa"/>
                              </div>
                            ))}

                          </>
                          : null
                        }
                      </div>
                  </div>
                  <div className='info'>
                    <div>
                      <strong>Data da festa:</strong>
                      <p>{moment(party.partyDate).format('DD/MM/YYYY')}</p>
                    </div>
                    <div>
                      <strong>Descrição:</strong>
                      <p>{party.description}</p>
                    </div>
                  </div>
                </div>
            </Wrapper>
        </div>
  )
}

export default PartyDetails

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const id = ctx.params?.id
  const { error, party } = await getPartyByIdRequest(id, ctx)
  if (error) {
    return {
      redirect: {
        destination: '/',
        permanent: false
      }
    }
  }

  return {
    props: {
      party
    }
  }
}
