import { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { parseCookies } from 'nookies'
import { getApiClient } from 'services/axios'

const Profile: NextPage = ({ user }: any) => {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Partytime | {user?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1>Profile</h1>
        <h1>{user?.name}</h1>
      </main>
    </div>
  )
}

export default Profile

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { 'auth-token': token } = parseCookies(ctx)

  const apiClient = getApiClient(ctx)

  if (!token) {
    return {
      redirect: {
        destination: '/',
        permanent: false
      }
    }
  }
  const response = await apiClient.get('api/user')

  return {
    props: {
      user: response.data.user
    }
  }
}
