import { NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'

const Profile: NextPage = () => {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Partytime</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1>Profile</h1>
      </main>
    </div>
  )
}

export default Profile
