import type { NextPage } from 'next'
import { useState, MouseEvent } from 'react'
import { useRouter } from 'next/router'
import { Wrapper } from './styles'
// Styles
import Head from 'next/head'
import { Form, Input } from 'assets/styles/form'
import { Button } from 'assets/styles/buttons'
import { Alert } from 'assets/styles/alert'

const Login: NextPage = () => {
  const router = useRouter()

  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [alert, setAlert] = useState<{msg: string, type?: string} | null>()

  const login = async (e: MouseEvent): Promise<void> => {
    e.preventDefault()

    const data = {
      email,
      password
    }

    const dataJSON = JSON.stringify(data)

    await fetch('http://localhost:3001/api/auth/login', {
      method: 'POST',
      headers: { 'Content-type': 'application/json' },
      body: dataJSON
    })
      .then((result) => result.json())
      .then((data) => {
        let auth = false

        if (data.error) {
          setAlert({ msg: data.error, type: 'danger' })
        } else {
          auth = true

          setAlert({ msg: data.msg })
          localStorage.setItem('auth-token', data.token)
          localStorage.setItem('userId', data.userId)
        }

        if (!auth) {
          setTimeout(() => {
            setAlert(null)
          }, 3000)
        } else {
          router.push('/')
        }
      })
  }
  return (
    <div>
      <Head>
        <title>Partytime | Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper className='container'>
        <h1>Acesse sua conta</h1>
        <h2>Coloque as suas informações para logar!</h2>
        <Form maxWidth={700}>
            <div>
              <label>Email</label>
              <Input placeholder='Coloque seu email' value={email} name='email' id='email' onChange={e => setEmail(e.target.value)}/>
            </div>
            <div>
              <label>Senha</label>
              <Input type='password' placeholder='Coloque sua senha' value={password} name='password' id='password' onChange={e => setPassword(e.target.value)}/>
            </div>
            <Button className='mt-5' onClick={e => login(e)}>Acessar</Button>
        </Form>
        {alert ? <Alert type={alert?.type}>{alert?.msg}</Alert> : null}
      </Wrapper>
  </div>
  )
}

export default Login
