import type { NextPage } from 'next'
import Navbar from 'components/Navbar'
import Head from 'next/head'
import { Wrapper } from './styles'
import { Form, Input } from 'assets/styles/form'
import { Button } from 'assets/styles/buttons'

const Register: NextPage = () => {
  return (
      <div>
      <Head>
        <title>Partytime | Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Wrapper className='container'>
        <h1>Crie uma conta</h1>
        <h2>Preencha o formulário para se cadastrar!</h2>
        <Form maxWidth={700}>
            <div>
              <label>Nome</label>
              <Input placeholder='Coloque seu nome' name='name' id='name'/>
            </div>
            <div>
              <label>Email</label>
              <Input placeholder='Coloque seu email' name='email' id='email'/>
            </div>
            <div>
              <label>Senha</label>
              <Input placeholder='Coloque sua senha' name='password' id='password'/>
            </div>
            <div>
              <label>Confirme sua senha</label>
              <Input placeholder='Confirme sua senha' name='confirmPassword' id='confirmPassword'/>
            </div>
            <Button className='mt-5'>Cadastrar</Button>
        </Form>
      </Wrapper>
  </div>
  )
}

export default Register
