import { useState, useContext } from 'react'
import Router from 'next/router'
import Head from 'next/head'
import { useForm } from 'react-hook-form'

import { AuthContext } from 'contexts/Auth/AuthContext'
// types
import { RegisterData } from 'contexts/Auth/AuthContext.d'

// Styles
import { Wrapper } from './styles'
import { Form, Input } from 'assets/styles/form'
import { Button } from 'assets/styles/buttons'
import { Alert } from 'assets/styles/alert'

const Register = () => {
  const { registerUser } = useContext(AuthContext)
  const { register, handleSubmit } = useForm()

  const [alert, setAlert] = useState<{msg: string, type?: string} | null>()

  const handleRegister = async (data): Promise<void> => {
    const { error, msg } = await registerUser(data)
    if (error) {
      setAlert({ msg: error, type: 'danger' })
      return
    }

    Router.push('/dashboard')
  }
  return (
      <div>
      <Head>
        <title>Partytime | Cadastro</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper className='container'>
        <h1>Crie uma conta</h1>
        <h2>Preencha o formulário para se cadastrar!</h2>
        <Form maxWidth={700} onSubmit={handleSubmit<RegisterData>(handleRegister)}>
            <div>
              <label>Nome</label>
              <Input
                {...register('name')}
                placeholder='Coloque seu nome'
                name='name'
                id='name'
                required
              />
            </div>
            <div>
              <label>Email</label>
              <Input
                {...register('email')}
                placeholder='Coloque seu email'
                type='email'
                name='email'
                id='email'
                required
              />
            </div>
            <div>
              <label>Senha</label>
              <Input
                {...register('password')}
                type='password'
                placeholder='Coloque sua senha'
                name='password'
                id='password'
                required
              />
            </div>
            <div>
              <label>Confirme sua senha</label>
              <Input
                {...register('confirmPassword')}
                type='password'
                placeholder='Confirme sua senha'
                name='confirmPassword'
                id='confirmPassword'
                required
              />
            </div>
            <Button className='mt-5'>Cadastrar</Button>
        </Form>
        {alert ? <Alert type={alert?.type}>{alert?.msg}</Alert> : null}
      </Wrapper>
  </div>
  )
}

export default Register
